### ISSUE TITLE
Deaths graph line is missing

### ISSUE THREAD

**Issue by alanocallaghan** [ShaneHastings/covid19.shanehastings.eu#2]
It seems to render on load and then vanish. Was going to fix it for you but the repo doesn't include that page yet. Mouseover still works https://covid19.shanehastings.eu/cases/

**Comment by ShaneHastings** [comment]
Thanks Alan, fixed this _somewhat_ now. Problem arose when they switched to weekly death reporting, and the charts library ApexCharts doesn't support skipping null values [#747](https://github.com/apexcharts/apexcharts.js/issues/747) so it just broke.

Not entirely happy with the fix but will leave for now. Will have a look at potentially switching that chart back to ChartJS or similar.

Will leave this open for now!

**Comment by alanocallaghan** [comment]
Nice, cheers! I've gotten good mileage out of plotly.js, though not sure if that's got any better handling of edge cases

**Comment by alanocallaghan** [comment]
Oh great work on the site btw, very helpful resource
